### ISSUE TITLE
Integration into HA core?

### ISSUE THREAD

**Issue by MatthiasLohr** [elupus/hass_nibe#134]
Hi,

I tried to check for similar tickets but couldn't find one, therefore here my question: Is there any specific reason why you don't want to add this integration to HA core?

I'm a HA contributor myself, highly interested in getting this integration into HA core, so if you agree, we could work together on getting your work into HA core. What do you think about that?

Best regards
Matthias

**Comment by elupus** [comment]
Just not been too find of the review experience :). Also i don't like some of my own design solutions for how it initializes (delays ha startup). That needs to be resolved before it can be mainlined.

Secondly it will need to ve mainlined in pieces since a big bang won't be accepted. That said, it would be nice to get it in.

**Comment by elupus** [comment]
Go for it!

**Comment by MatthiasLohr** [comment]
Meeh. Just discovered: My new NIBE devices are using the new myUplink API. This raises the question: Should we try to combine it all in one python library (by extending your `nibeuplink` package) and HA integration, or should that be done in seperate integrations/libraries?

**Comment by Chrille144** [comment]
Hey,

Has there been any progress in getting this integration in Core? Any timeline?

Thanks for all the hard work!
/C

**Comment by elupus** [comment]
Nope.

**Comment by elupus** [comment]
This will never be merged to core since it's being deprecated by nibe. There is a new myuplink in core for those that have had their pumps upgraded.
