### ISSUE TITLE
Switching to myUplink or not?

### ISSUE THREAD

**Issue by bohtho** [elupus/hass_nibe#202]
Just a got an email from Nibe that my system can now upgrade from NibeUplink to myUplink, and is wondering whether this is a good idea feature wise, and whether this component will also now switch Nibe API?

**Comment by elupus** [comment]
This component will not. But there is ongoing work (by another) to support myuplink in home assistant. I suggest holding of a little.

**Comment by bohtho** [comment]
Thanks for valuable input!

Another somewhat related thing is that I fear, but don't know for certain before I actually switch to myUplink, that the "smart thermostats" feature is missing there. I currently pass on 3 datapoints per room/radiator in my house every time they change (through the service provided by this component and a registered application on api.nibeuplink.com), and the API does some "magic" on these and present a compound status and demand for the whole house to the heat pump.

Do you or anybody know whether it's possible to continue updating this in a somewhat similar fashion with myUplink?

**Comment by bohtho** [comment]
> > I had exactly the same question as @bohtho so I'll defer upgrading to myUplink for now. Out of interest, is the ongoing work you alluded to part of the NIBE Heat Pump integration (https://www.home-assistant.io/integrations/nibe_heatpump)?

That standard component communicates via RS483 and/or ModBus. I would assume he was referring to this one: https://github.com/jaroschek/home-assistant-myuplink

**Comment by marcusthorstrom** [comment]
I switched yesterday to myUplink (official from 2024.2 nor HASS) and I will go back today as the smart thermostats feature is missing.
I also looked at the API for myUplink vs Nibe Uplink, and there is no endpoint to set thermostats in myUplink. So unless they add that endpoint to myUplink it will not be possible to use smart thermostats.

What myUplink does better is the rate that parameters is updated, its every minute now instead. With Nibe Uplink the power consumption for the compressor and water heater was updated every 70th minute, but those values is missing in myUplink.

**Comment by AnonymousRetard** [comment]
I registered a myUplink account on the 8th of February and used the contact for to report a bug about the consumption for compressor and water heater missing. I was told they sent my request to their developers for future updates and improvements but they also told me that after summer 2024 they will close down NIBE uplink and therefore recommended me to proceed with the update I have currently held off on because of this.

I answered that I will delay the upgrade as long as possible until I am made aware that these fields now exist in myUplink as well. I don't feel so secure that it will happen but maybe it helps if more of you also try to contact NIBE about it?

**Comment by Marrrs** [comment]
I'll just add my two eurocents here since I have been hesitant moving to the MyUplink and the native HA integration for it after reading the comments here. I have a F730 and I updated it to the latest firmware, which transfered it to MyUplink. I had to wait maybe 30 min for it to show up in their app. Setting up the rest was a breeze and I was happy that the entities was aptly named so it was easy to change the automations and dashboard items as needed. I don't have a Nibe subscription so I only use HA for sensor readings. The native integration loads fast and the connection to MyUplink seems stable, for my use case the move to MyUplink has been a success without downsides.

That said, after using the hass_nibe integration also without issues for almost four years, I want to thank @elupus from the bottom of my heart. I actually found HA when looking for a way to get better readings from the F730 and I was blown away by the amount of sensors it provided. It has has been a joy to figure out how to make best use of all the data provided from hass_nibe. I have unsuccessfully been looking for a "buy me a coffe/beer" link or similar, but the next best I could come up with is just thanking the project owner for putting in so much work inte this project. Effectively it is saving money for us Nibe users, and also helps people like me with a bit of FOMO relief during the cold (read expensive) winter months up here in the north. 

Thank you @elupus and other persons involved in the project!

**Comment by elupus** [comment]
It warms my heart to hear! Thanks for the writeup!

**Comment by imist** [comment]
Well said @Marrrs, I cheer in in the tribute!

**Comment by Delph1** [comment]
I second the tribute to @elupus Grade A plugin and support really.

**Comment by SimonLeigh** [comment]
Thank you to @elupus for such a great integration and support. Worked flawlessly with my F1145 for two years. The smart thermostats integration made a big different to my home comfort once I had it working this last winter.

I have messaged NIBE letting them know that myUplink not having the API for smart thermostats is a big step back and that they should fix it. In any case, they have forced us to upgrade, but at least we can try to apply some pressure if we leverage that feature as it really affects household comfort.

**Comment by stepanv** [comment]
Hi everyone, I got an email from Nibe, that the "Connection to NIBE Uplink will be broken on August 30, 2024".
My understanding is that NIBE will shut down https://www.nibeuplink.com in 3 weeks so I'm confused why you still develop and release this feature?

By any chance, does it mean, either
* you somehow know nibeuplink.com will continue to work even after August 2024
* this feature will work against myuplink.com

?

Thanks for this integration, it perfectly worked in last few years!

**Comment by elupus** [comment]
I've not upgraded my pump yet. It will not work against my uplink. 
Had not received a shutdown notice, so did not know about the deadline.

**Comment by nickcj931** [comment]
Yep can confirm ive just received a "Last reminder" threat from NIBE to switch or i lose all functionality "the connection to NIBE Uplink will be broken on August 30, 2024" 

Joke... given the price i paid for my equipment... now i cant send dynamic Thermostat readings to influence the temperature calculation on the unit :( 

Also echo everyone above thanks for all the hard work @elupus  this has been such a great integration for our house and made such a difference to our efficiencies, sadly this is no more.

**Comment by nickcj931** [comment]
@bohtho  - i have actually received a reply from myUplink its not helpful but for reference - they said they passed the feedback to developers however failed to answer any questions i had which is the same as you - I picked NIBE for the pure function of being able to pass my already in place thermostats/zones to the heatpump to essentially make it more efficient in operation - and this change has removed features which was one of main purchasing driving decisions for me (and sounds like you as well) to invest in their heat pump. 

After I challenged the lack of response to that issue he suggest I contact Nibe (which is who i thought i was contacting! email address for reference help.myuplink@nibe.se) 

I am actually in process of figuring out any legal path as I'm pretty sure this is a breach of consumer protection act and contract of sale in the UK.

**Comment by Delph1** [comment]
@nickcj931 MyUplink is run by a company called Myuptech AB (556633-8140), which is a subsidiary of Nibe. Why they have chosen to have this pretty crucial technology in a separate entity is beyond me, but it answers the question as to why they asked you to talk to Nibe. It's not exactly crystal clear that they are two different companies, but they are.

**Comment by nickcj931** [comment]
@Delph1  - thats interesting to know thanks for the flag will add that into the armory.... However from a consumer point of view, which is what we all are, we paid NIBE for a service and product - which is now inferior to what was purchased based on decisions they made internally. The fact that they chose to complicate their company structure isnt really a concern of ours since our business is with NIBE fundamentally.

**Comment by Delph1** [comment]
@Delph1 Agree 100%. I just wanted to add some facts and context. More people are going to get upset about this sooner rather than later. The more people that complain to BOTH companies, the better.

**Comment by nickcj931** [comment]
Hi all just wanted to put this here so other people know.

Ive heard back from myUplink team with an update this is a copy and paste from their email received 4th Sep 2024

```
Hi

We have discussed your feedback further within the organization and decided to introduce a similar function via our open api also on myUplink, our developers have started to look at it and hopefully we can release a function later this year, we will get back to you when we have a function ready.

Have a nice day!
Team myUplink.
```

Fingers crossed we can have full functionality resotred!

**Comment by imist** [comment]
Sounds very interesting and promising! Which missing functions did you ask for?

**Comment by nickcj931** [comment]
Ability to pass remote thermostat function like the old uplink API used to let you do.

**Comment by SimonLeigh** [comment]
@nickcj931 good to hear. I will also email help.myuplink@nibe.se as I was "fobbed off" with the response they had passed it to their developers and was met with silence when I noted they would make a material difference to the comfort and warmth of my home this winter as a consequence of removing necessary features.
