### ISSUE TITLE
the . is placed wrong

### ISSUE THREAD

**Issue by mrlook2** [elupus/hass_nibe#5]
I get some values wrong. 

for example the max fuse size says 1.6A but should be 16A
timefactor says 2929.0h but should be 292.9h
![nibe](https://user-images.githubusercontent.com/14833143/39628557-bf54a6f8-4fa9-11e8-83e8-8c730b166401.png)

**Comment by elupus** [comment]
Yes. That is solved on the branch called "module" if I remember correctly.

**Comment by mrlook2** [comment]
sorry, I might be stupid but I don't realy understand. 
Where and how do I fix this ?

**Comment by elupus** [comment]
It is solved in the branch called "module" in git. https://github.com/elupus/hass_nibe/tree/module. To switch after you clone the module you can issue the command: `git checkout -b module origin/module` be sure to read the readme on the above link since the configuration is somewhat different and you will need to install an additional python module in your home assistant environment.
